project:
  type: website

website:
  title: "Happy Hideouts"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Project Proposal" 
        href: "projectproposal.html"


format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual

