project:
  type: website

website:
  title: "gaproject"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Project Proposal" 
        href: "projectproposal.html"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

